[connections.snowflake]
account = "FHHGLFA-GSB16888"
user = "PETETRIAL"
password = "1pqK4FcO&9^*@qaY"
#private_key_file = "../xxx/xxx.p8"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
